// validator.js 13.12.0, a subset of 48 functions (see README.md).
import isEmail from './lib/isEmail.js';
import isFQDN from './lib/isFQDN.js';
import isIP from './lib/isIP.js';
import isURL from './lib/isURL.js';
import isByteLength from './lib/isByteLength.js';
import isIPRange from './lib/isIPRange.js';
import isMACAddress from './lib/isMACAddress.js';
import isPort from './lib/isPort.js';
import isInt from './lib/isInt.js';
import isLength from './lib/isLength.js';
import isHexadecimal from './lib/isHexadecimal.js';
import isBase64 from './lib/isBase64.js';
import isJWT from './lib/isJWT.js';
import isUUID from './lib/isUUID.js';
import isSlug from './lib/isSlug.js';
import isEmpty from './lib/isEmpty.js';
import contains from './lib/contains.js';
import equals from './lib/equals.js';
import escape from './lib/escape.js';
import unescape from './lib/unescape.js';
import trim from './lib/trim.js';
import ltrim from './lib/ltrim.js';
import rtrim from './lib/rtrim.js';
import toInt from './lib/toInt.js';
import toFloat from './lib/toFloat.js';
import toBoolean from './lib/toBoolean.js';
import blacklist from './lib/blacklist.js';
import whitelist from './lib/whitelist.js';
import stripLow from './lib/stripLow.js';
import isAscii from './lib/isAscii.js';
import isLowercase from './lib/isLowercase.js';
import isUppercase from './lib/isUppercase.js';
import isIn from './lib/isIn.js';
import isDataURI from './lib/isDataURI.js';
import isMimeType from './lib/isMimeType.js';
import isSemVer from './lib/isSemVer.js';
import isHash from './lib/isHash.js';
import isMD5 from './lib/isMD5.js';
import isAlpha from './lib/isAlpha.js';
import isAlphanumeric from './lib/isAlphanumeric.js';
import isNumeric from './lib/isNumeric.js';
import isDecimal from './lib/isDecimal.js';
import isFloat from './lib/isFloat.js';
import isBoolean from './lib/isBoolean.js';
import isJSON from './lib/isJSON.js';
import isHexColor from './lib/isHexColor.js';
import isLatLong from './lib/isLatLong.js';
import isMagnetURI from './lib/isMagnetURI.js';

export const version = '13.12.0';
export { isEmail, isFQDN, isIP, isURL, isByteLength, isIPRange, isMACAddress, isPort, isInt, isLength, isHexadecimal, isBase64, isJWT, isUUID, isSlug, isEmpty, contains, equals, escape, unescape, trim, ltrim, rtrim, toInt, toFloat, toBoolean, blacklist, whitelist, stripLow, isAscii, isLowercase, isUppercase, isIn, isDataURI, isMimeType, isSemVer, isHash, isMD5, isAlpha, isAlphanumeric, isNumeric, isDecimal, isFloat, isBoolean, isJSON, isHexColor, isLatLong, isMagnetURI };

const validator = { version, isEmail, isFQDN, isIP, isURL, isByteLength, isIPRange, isMACAddress, isPort, isInt, isLength, isHexadecimal, isBase64, isJWT, isUUID, isSlug, isEmpty, contains, equals, escape, unescape, trim, ltrim, rtrim, toInt, toFloat, toBoolean, blacklist, whitelist, stripLow, isAscii, isLowercase, isUppercase, isIn, isDataURI, isMimeType, isSemVer, isHash, isMD5, isAlpha, isAlphanumeric, isNumeric, isDecimal, isFloat, isBoolean, isJSON, isHexColor, isLatLong, isMagnetURI };
export default validator;
