// Bundles work.js + work.css into assets.gen.ts (strings the Worker serves inline).
// Run after editing either: node src/landingui/build.mjs
import { readFileSync, writeFileSync } from 'node:fs';
const here = (f) => new URL(f, import.meta.url);
const js = readFileSync(here('work.js'), 'utf8'), css = readFileSync(here('work.css'), 'utf8');
const labJs = readFileSync(here('lab.js'), 'utf8'), labCss = readFileSync(here('lab.css'), 'utf8');
if (/<\/script/i.test(js + labJs) || /<\/style/i.test(css + labCss)) throw new Error('closing tag inside an inline asset');
writeFileSync(here('assets.gen.ts'), `// GENERATED by src/landingui/build.mjs from work.js, work.css, lab.js and lab.css. Do not edit.\nexport const WORK_JS = ${JSON.stringify(js)};\nexport const WORK_CSS = ${JSON.stringify(css)};\nexport const LAB_JS = ${JSON.stringify(labJs)};\nexport const LAB_CSS = ${JSON.stringify(labCss)};\n`);
console.log(`assets.gen.ts: work js ${js.length} B css ${css.length} B; lab js ${labJs.length} B css ${labCss.length} B`);
