// Bundles work.js + work.css into assets.gen.ts (strings the Worker serves inline).
// Run after editing either: node src/landingui/build.mjs
import { readFileSync, writeFileSync } from 'node:fs';
const here = (f) => new URL(f, import.meta.url);
const js = readFileSync(here('work.js'), 'utf8'), css = readFileSync(here('work.css'), 'utf8');
if (/<\/script/i.test(js) || /<\/style/i.test(css)) throw new Error('closing tag inside an inline asset');
writeFileSync(here('assets.gen.ts'), `// GENERATED by src/landingui/build.mjs from work.js and work.css. Do not edit.\nexport const WORK_JS = ${JSON.stringify(js)};\nexport const WORK_CSS = ${JSON.stringify(css)};\n`);
console.log(`assets.gen.ts: js ${js.length} B, css ${css.length} B`);
